### PR TITLE
Setting up Cypress

### PR DESCRIPTION
**Pull request by elvitak**
create cypress fixtures and integration files by running 'yarn cypress'
delete example files

### CODE REVIEW

**Review by tochman — COMMENTED** [review]
What version of Cypress are you using?

**Comment by elvitak** [comment]
was 4.0.2 changed to 9.1.1

**Comment by lukeperrin10** [comment]
Just to point out, you've not only updated cypress here but a few other dependencies as well.

**Review by lukeperrin10 — APPROVED** [review]
Looks good to me now, like I said in future be accurate with your PRs 😃

**Review by tochman — APPROVED** [review]

**Pull request merged**
